### ISSUE TITLE
Crash when calling electron log from on-before-quit

### ISSUE THREAD

**Issue by pronebird** [megahertz/electron-log#136]
Calling `log.info('onBeforeQuit');` from `on-before-quit` event handler causes a crash:

```
(node:7016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of null
    at ~/node_modules/electron-log/lib/utils.js:103:21
    at Array.forEach (<anonymous>)
    at Object.sendIpcToRenderer (~/node_modules/electron-log/lib/utils.js:102:42)
    at Object.transport [as rendererConsole] (~/node_modules/electron-log/lib/transports/rendererConsole.js:39:11)
    at log (~/node_modules/electron-log/lib/log.js:25:20)
```

Basically what I do is destroy the only window I have.

**Comment by megahertz** [comment]
Thank you, will fix on the next week.
