### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by SergeyBelikof** [megahertz/electron-log#175]
Create simple electron application:

```
const log = require('electron-log');
Object.assign(console, log.functions);

var circularReference = {otherData: 123};
circularReference.myself = circularReference;
console.info(circularReference);
```

Try log circular reference. Got an error.

Uncaught Exception:
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at toJSON (C:\Users\sbelikov\Desktop\electron-quick-start-master\node_modules\electron-log\src\transform\object.js:97:26)
    at C:\Users\sbelikov\Desktop\electron-quick-start-master\node_modules\electron-log\src\transform\index.js:43:12
    at Array.reduce (<anonymous>)
    at Object.transform (C:\Users\sbelikov\Desktop\electron-quick-start-master\node_modules\electron-log\src\transform\index.js:42:23)
    at transport (C:\Users\sbelikov\Desktop\electron-quick-start-master\node_modules\electron-log\src\transports\console.js:45:35)
    at runTransport (C:\Users\sbelikov\Desktop\electron-quick-start-master\node_modules\electron-log\src\log.js:43:5)
    at runTransports (C:\Users\sbelikov\Desktop\electron-quick-start-master\node_modules\electron-log\src\log.js:26:7)
    at log (C:\Users\sbelikov\Desktop\electron-quick-start-master\node_modules\electron-log\src\log.js:20:3)
    at Object.<anonymous> (C:\Users\sbelikov\Desktop\electron-quick-start-master\main.js:9:9)

![image](https://user-images.githubusercontent.com/18127649/71510372-bf24ea00-289f-11ea-9049-89d9e323eb8f.png)

Test repo: https://github.com/SergeyBelikof/electron-log-circular-bug

**Comment by megahertz** [comment]
Thank you for the report!
