### ISSUE TITLE
Unable to install using npm

### ISSUE THREAD

**Issue by ilsme** [megahertz/electron-log#219]
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   '--verbose',
npm verb cli   'install',
npm verb cli   'electron-log'
npm verb cli ]
npm info using npm@6.14.6
npm info using node@v12.18.3
npm verb npm-session 58815472c2710833
npm http fetch GET 304 https://registry.npmjs.org/electron-log 474ms (from cache)
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 503ms
npm verb stack SyntaxError: Unexpected end of JSON input while parsing near '...sSAnZWagAAVIwP/2onLsn'
npm verb stack     at JSON.parse (<anonymous>)
npm verb stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
npm verb stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm verb cwd /tmp/
npm verb Linux 5.4.0-49-generic
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "--verbose" "install" "electron-log"
npm verb node v12.18.3
npm verb npm  v6.14.6
npm ERR! Unexpected end of JSON input while parsing near '...sSAnZWagAAVIwP/2onLsn'
npm verb exit [ 1, true ]
npm timing npm Completed in 746ms

```

**Comment by megahertz** [comment]
The issue is not related to the library, something goes wrong with npm.
Try
`npm i --force electron-log`

and if it's not helpful:
`rm -rf node_modules && npm i`
