### ISSUE TITLE
Electron 16: The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by DanielMcAssey** [megahertz/electron-log#293]
Getting the following error on the renderer process when calling `electronLog.create('my-new-log');`

```
Uncaught TypeError: The "path" argument must be of type string. Received null
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:429:7)
    at getUserData (http://localhost:4200/main.js:20629:50)
    at getLibraryDefaultDir (http://localhost:4200/main.js:20559:20)
    at Object.getPathVariables (http://localhost:4200/main.js:20617:24)
    at fileTransportFactory (http://localhost:4200/main.js:20236:33)
    at create (http://localhost:4200/main.js:19037:11)
    at Object.31194 (http://localhost:4200/main.js:19005:18)
    at __webpack_require__ (http://localhost:4200/runtime.js:23:42)
    at Module.41577 (http://localhost:4200/main.js:87763:70)
    at __webpack_require__ (http://localhost:4200/runtime.js:23:42)
    at Module.99125 (http://localhost:4200/main.js:88346:84)
    at __webpack_require__ (http://localhost:4200/runtime.js:23:42)
    at Module.13548 (http://localhost:4200/main.js:86504:67)
    at __webpack_require__ (http://localhost:4200/runtime.js:23:42)
    at Module.9427 (http://localhost:4200/main.js:86211:86)
    at __webpack_require__ (http://localhost:4200/runtime.js:23:42)
    at Module.87722 (http://localhost:4200/main.js:83682:75)
    at __webpack_require__ (http://localhost:4200/runtime.js:23:42)
    at Module.62141 (http://localhost:4200/main.js:91749:73)
    at __webpack_require__ (http://localhost:4200/runtime.js:23:42)
    at __webpack_exec__ (http://localhost:4200/main.js:251247:48)
    at http://localhost:4200/main.js:251248:62
    at webpackJsonpCallback (http://localhost:4200/runtime.js:290:38)
    at http://localhost:4200/main.js:1:87
```

I believe this is because in Electron 16 when calling getApp() in [electronApi](https://github.com/megahertz/electron-log/blob/6c184a139c929bcdc20d1ccfc8524a167a317205/src/electronApi.js#L34), the app variable no longer exists on the renderer context

**Comment by megahertz** [comment]
Normally, it works fine even if remote module is unavailable. What's the OS?

**Comment by DanielMcAssey** [comment]
This is Windows 10, 64-bit
