### ISSUE TITLE
RangeError: Maximum call stack size exceeded at defineProperty (native)

### ISSUE THREAD

**Issue by crucialfelix** [megahertz/electron-log#3]
This works great in development, but when I build a release it fails as shown below.

Electron 1.2.3
"electron-prebuilt": "^1.2.3",

const log = require('electron-log');
log.debug('synthDefsDir', '/some/path');

```
Uncaught Exception:
RangeError: Maximum call stack size exceeded
    at defineProperty (native)
    at r (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:66:1)
    at e (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:181:1)
    at s (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:138:1)
    at Object.u (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:110:1)
    at r (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:87:1)
    at e (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:181:1)
    at s (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:138:1)
    at Object.u (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:110:1)
    at r (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:87:1)
    at e (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:181:1)
    at s (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:138:1)
    at Object.u (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:110:1)
    at r (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:87:1)
    at e (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:181:1)
    at s (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:138:1)
    at Object.u (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:110:1)
    at r (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:87:1)
    at e (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:181:1)
    at s (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:138:1)
    at Object.u (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:110:1)
    at r (/Users/crucial/code/idmx/playsplom/release/darwin-x64/PlaySPLOM-darwin-x64/PlaySPLOM.app/Contents/Resources/app/webpack:/~/electron-log/index.js:87:1)
```

**Comment by crucialfelix** [comment]
Did this have to do with not being able to read the package.json ? I guess there wouldn't have been one inside the app at that point.

thanks for the fix.

**Comment by megahertz** [comment]
Thank you for the report. If you have no package.json in your build, you can specify appName property (see a File Transport section in readme).
