### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lfpei** [megahertz/electron-log#311]
Error:
```RangeError: Maximum call stack size exceeded
    at Object.<anonymous> (/Users/workspace/node_modules/electron-log/src/transform/object.js:20:19)
    at JSON.stringify (<anonymous>)
    at toJSON (/Users/workspace/node_modules/electron-log/src/transform/object.js:137:26)
    at /Users/workspace/node_modules/electron-log/src/transform/index.js:47:14
    at Array.reduce (<anonymous>)
    at Object.transform (/Users/workspace/node_modules/electron-log/src/transform/index.js:45:23)
    at transport (/Users/workspace/node_modules/electron-log/src/transports/ipc.js:34:23)
    at runTransport (/Users/workspace/node_modules/electron-log/src/log.js:44:5)
    at runTransports (/Users/workspace/node_modules/electron-log/src/log.js:27:7)
    at log (/Users/workspace/node_modules/electron-log/src/log.js:21:3)
```
OS: macOS 10.15

When I use tinymce to listen to the 'keydown' event, I get stuck in an infinite loop

<img width="642" alt="image" src="https://user-images.githubusercontent.com/40376166/179382852-f3a6f0ff-d368-4e24-94ad-5c857cb16c6b.png">

**Comment by megahertz** [comment]
It's hard to determine the actual reason without an example. Sometimes some proxy objects may produce similar value but with a different reference and it's not possible to detect such a case. Anyway, it's better to prevent event logging, since it's often a huge nested object which may impact on performance. And make sure you use the latest lib version since I've added a few optimizations there

**Comment by lfpei** [comment]
I am using electron-log 4.4.8
<img width="790" alt="image" src="https://user-images.githubusercontent.com/40376166/179386283-b84eb662-14e2-4215-a175-7b56eae14c96.png">

```js
window.addEventListener('keydown', (e) => {
    console.log(e)
 })
editor.on('keyup', (e) => {
    console.log(e)
})
```
The two results are as shown above; There is no problem with window listening for events，but tinymce doesn't work properly

**Comment by megahertz** [comment]
A renderer part was fully changed in v5, so it may solve the issue. Please let me know if it still happens in v5.
