### ISSUE TITLE
Got a error "data.map is not a function" when I custom a transport.file.format. 

### ISSUE THREAD

**Issue by c0010c** [megahertz/electron-log#422]
Version:5.1.5
Stack:
Unhandled electron-log error TypeError: data.map is not a function
    at toString (D:\dev\webWS\game-rcsc-electron\node_modules\electron-log\src\node\transforms\object.js:63:33)
    at D:\dev\webWS\game-rcsc-electron\node_modules\electron-log\src\node\transforms\transform.js:15:14
    at Array.reduce (<anonymous>)
    at transform (D:\dev\webWS\game-rcsc-electron\node_modules\electron-log\src\node\transforms\transform.js:13:21)
    at transport (D:\dev\webWS\game-rcsc-electron\node_modules\electron-log\src\node\transports\file\index.js:74:21)
    at Logger.processMessage (D:\dev\webWS\game-rcsc-electron\node_modules\electron-log\src\core\Logger.js:173:11)
    at Logger.logData (D:\dev\webWS\game-rcsc-electron\node_modules\electron-log\src\core\Logger.js:129:10)
    at <computed> [as info] (D:\dev\webWS\game-rcsc-electron\node_modules\electron-log\src\core\Logger.js:83:37)
    
    
    
![image](https://github.com/megahertz/electron-log/assets/26128811/0658a4c8-995f-4209-9b99-cb2506300fe1)

**Comment by megahertz** [comment]
Could you show your logger initialization code?
