### ISSUE TITLE
Windows 10 writes logs as temp files

### ISSUE THREAD

**Issue by pbmzero** [megahertz/electron-log#78]
Hi,
electron-log is working until i run it through electron-builder, then install in windows 10.

Per the documentation i expect the logs to go to `%USERPROFILE%\AppData\Roaming\<app name>\myapp.log` however it's going to random file names in temp `C:\users\username\AppData\Local\Temp\326a7c0b-f4c7-4591-86cd-c8bfa2b5db37.tmp.log`

Below is my setup

Thanks in advance

Paul

```
{
  "name": "myapp",
  "productName": "myapp",
  "version": "1.0.0",
  "description": "myapp",
  "main": "main.js",
  "build": {
    "directories": {
      "buildResources": "./build/images"
    },
    "icon": "./build/images/icon.ico"
  },
  "scripts": {
    "start": "electron .",
    "build": "./node_modules/.bin/electron-builder",
  },
  "author": "",
  "license": "UNLICENSED",
  "devDependencies": {
    "electron": "^1.8.6",
    "electron-builder": "^20.13.3",
  },
  "dependencies": {
    "electron-log": "^2.2.14",
  }
}

```

```
logger.transports.file.level = 'info';
logger.transports.file.maxSize = 5 * 1024 * 1024;
logger.transports.file.appName = 'myapp';
logger.transports.file.file = __dirname + '/myapp.log';
logger.transports.file.streamConfig = {flags: 'a'};
logger.transports.file.stream = fs.createWriteStream(logger.transports.file.file, logger.transports.file.streamConfig);
```

**Comment by megahertz** [comment]
Hi, it's very strange, i haven't seen such a report before. Maybe some other ecectron library override this option? Try to run the following code in the top of entry point script:
```js
Object.defineProperties(logger.transports.file, {
  file: {
    get() {
      console.log('Getting logger.transports.file.file', this._file);
      return this._file;
    },
    set(value) {
      this._file = value;
      console.log('Setting logger.transports.file.file', value);
    },
  },
  stream: {
    get() {
      console.log('Getting logger.transports.file.stream', this._file);
      return this._stream;
    },
    set(value) {
      this._stream = value;
      console.log('Setting logger.transports.file.stream', value);
    },
  },
});
```
You'll see if it's overriden in some other places.

**Comment by pbmzero** [comment]
Alexey,

On the production build from electron-builder i'm getting the following popup error message frequently which stops the app from beginning:
`Uncaught Exception.  Error: ENOENT, myapp.log not found in c:\Users\My User\Local\Programs\myapp\resources\app.asar
   at notFoundError (ELECTRON_ASR.js:114:19)
   at ObjectModule.(anonymous function [as open] (ELECTRON_ASR.js:214:16)
   at WriteStream.open (fs.js2111:6)
   at new WriteStream (fs.js2097:10)
   at Object.fs.createWriteStream (fs.js:2059:10)
   at setupLogger (C:\users\My User\AppData\Local\Programs\myapp\resources\app.asr\...:37) at App.createWindow
 (C:\users\My User\AppData\Local\Programs\myapp\resources\app.asr\...:4)
   at emitTwo (events.js:130:20)
   at App.empt (events.js:213:7)
`


Here is what i see when i run from dev mode with the debugger:

```
Getting logger.transports.file.stream undefined
Getting logger.transports.file.file undefined
Setting logger.transports.file.file C:\Users\My User\AppData\Roaming\myapp\log.log
Getting logger.transports.file.file C:\Users\My User\AppData\Roaming\myapp\log.log
Getting logger.transports.file.file C:\Users\My User\AppData\Roaming\myapp\log.log
Setting logger.transports.file.stream WriteStream {
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  domain: null,
  _events: { finish: { [Function: bound onceWrapper] listener: [Function] } },
  _eventsCount: 1,
  _maxListeners: undefined,
  path: 'C:\\Users\\My User\\AppData\\Roaming\\myapp\\log.log',
  fd: null,
  flags: 'a',
  mode: 438,
  start: undefined,
  autoClose: true,
  pos: undefined,
  bytesWritten: 0 }
Getting logger.transports.file.stream C:\Users\My User\AppData\Roaming\myapp\log.log
Getting logger.transports.file.stream C:\Users\My User\AppData\Roaming\myapp\log.log
[09:59:19.014] [info] Initial State

```

**Comment by megahertz** [comment]
I think it's because you override file option. I don't know exactly  how `__dirname + '/myapp.log';` is resolved in compiled application, but i think it should be resolved to asar package, and then into temporary path. So, I can only recommend to use another path or leave this option default.

**Comment by megahertz** [comment]
Try v3.0.0-beta2 with default file transport settings.
